title: "Tilden \"Tilly\" Brooks"
email: teb44@stanford.edu
description: >
  Researcher interested in the interface of linguistics and law.

#remote_theme: poole/hyde
#plugins:
# - jekyll-remote-theme

theme: minima
plugins:
   - jekyll-feed

header_pages:
  - index.md
  - about.markdown
  - research.md


  
# Optional links for the sidebar
sidebar_links:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: About
    url: /about/
  - title: Blog
    url: /blog/

# Other optional settings
baseurl: ""
url: ""
