title: "Tilden \"Tilly\" Brooks"
email: teb44@stanford.edu
description: >
  Researcher interested in the interface of linguistics and law.

remote_theme: poole/hyde
plugins:
  - jekyll-remote-theme

# Optional links for the sidebar
sidebar_links:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: Presentations
    url: /presentations/
  - title: Blog
    url: /blog/

# Other optional settings
baseurl: ""
url: ""
