title: "Tilden 'Tilly' Brooks"
description: Linguistics · Law · Semantics · Pragmatics

remote_theme: poole/hyde
plugins:
  - jekyll-remote-theme

sidebar_links:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: Research
    url: /research/
  - title: Blog
    url: /blog/
